backend:
  name: Lorna Jane BOS
  repo: owner/repo # Path to your Github repository
  branch: gh-pages # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "ljbos" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Content" # Used in the UI, e.g., "New Post"
    folder: "ljbos/a06d079f88fba06b5ea8daf73d20830786d8f767/" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Foo", name: "foo", widget: "foo"}
      - {label: "Publish Date", name: "date", widget: "datetime"}